export const accountActionTypes = {
    SET_USER: 'ACCOUNT.SET_USER',
    SET_SCHEME: 'ACCOUNT.SET_SCHEME',
}
export const viewsActionTypes = {
    SET_ACTIVE_STORY: 'VIEWS.SET_ACTIVE_STORY',
    SET_ACTIVE_PANEL: 'VIEWS.SET_ACTIVE_PANEL',
    SET_ACTIVE_SCENE: 'VIEWS.SET_ACTIVE_SCENE',
    SET_HISTORY: 'VIEWS.SET_HISTORY',
    SET_NEED_EPIC: 'VIEWS.SET_NEED_EPIC',
    SET_SNACKBAR: 'VIEWS.SET_SNACKBAR',
}

export const faqActionTypes = {
    SET_ACTIVE_TAB: 'FAQ.SET_ACTIVE_TAB',
    SET_CATEGORIES: 'FAQ.SET_CATEGORIES',
    SET_QUESTIONS: 'FAQ.SET_QUESTIONS',
    SET_ACTIVE_CATEGORY: 'FAQ.SET_ACTIVE_CATEGORY',
    SET_ACTIVE_QUESTION: 'FAQ.SET_ACTIVE_QUESTION',
    SET_SEARCH_RESULT_QUESTION: 'FAQ.SET_SEARCH_RESULT_QUESTION',

}
