# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: 
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3.2.0
      with:
        node-version: 14
        cache: 'npm'
        cache-dependency-path: app_desktop/package-lock.json
    - run: set -eu
    - run: mkdir "$HOME/.ssh"
    - run: echo "${{ secrets.SSH_KEY }}" > "$HOME/.ssh/SSH_KEY"
    - run: chmod 600 "$HOME/.ssh/SSH_KEY"
    - name: Building Desktop
      run: |
        cd app_desktop
        npm ci
        npm run build
    - name: Building Mobile
      run: |
        cd mobile
        npm ci
        npm run build
        cd build
        zip -r odr.zip *
    - name: Deploing
      run: |
        rsync -e "ssh -i $HOME/.ssh/SSH_KEY -o StrictHostKeyChecking=no" --archive --compress --delete ./mobile/buld/* root@89.223.126.48:/var/www/xelene.ru/experts_guide/mobile
        rsync -e "ssh -i $HOME/.ssh/SSH_KEY -o StrictHostKeyChecking=no" --archive --compress --delete ./app_desktop/buld/* root@89.223.126.48:/var/www/xelene.ru/experts_guide/desktop
        rsync -e "ssh -i $HOME/.ssh/SSH_KEY -o StrictHostKeyChecking=no" --archive --compress --delete ./php root@89.223.126.48:/var/www/xelene.ru/experts_guide
